apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    app: mongodb
    tier: db
    project: roboshop 
spec:
  selector:
    matchLabels:
      app: mongodb
      tier: db
      project: roboshop
  serviceName: "mongodb"
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
        tier: db
        project: roboshop
    spec:
      containers:
      - name: praveenkothapally/mongodb:1.0.0
        image: nginx
        #Now below steps are importent 
        volumeMounts:
        - name: mongodb
          mountPath: /data/db
  # this is PVC directly.
  volumeClaimTemplates:
  - metadata:
      name: mongodb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-dynamic-ebs"
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  clusterIP: None #you have to mention cluster ip should be none in headless
  selector:
    app: mongodb
    tier: db
    project: roboshop
  ports:
  - name: mongodb-port
    protocol: TCP
    port: 27017 # this port belongs to service
    targetPort: 27017 # this port belongs to (pod or container)